
name: FactionPlugin
version: 1.0
main: org.derjannik.FactionPlugin.FactionPlugin
api-version: 1.21

commands:
  chooseclass:
    description: Choose your player class
    usage: /<command> <classname>
  joinfaction:
    description: Join a faction
    usage: /<command> <factionname>
  leavefaction:
    description: Leave your current faction
    usage: /<command>
  setcosmetic:
    description: Set a cosmetic item
    usage: /<command> <type> <item>
  getcosmetic:
    description: Get your current cosmetic item
    usage: /<command> <type>
  factioninfo:
    description: Get information about your current faction
    usage: /<command>
